### ISSUE TITLE
Allow DecAssign in the conditional clause of if statements?

### ISSUE THREAD

**Issue by tgomezzzz** [raghavmecheri/viper#37]
Right now, this code throws a parse error:
```
if (bool b = true) {
    print();
}
```

This case is pretty stupid, but for DecAssign on other types, it'll allow for nice things like
```
if (int r = sock.recv()){
    print(r);
}
```

We might also consider allowing for other expression types (calls seem like they might be nice)
```
if (list.isEmpty()){
    return
}
```

**Comment by hmontero1205** [comment]
Would the declaration (first two examples) be available in the outside scope? or just inside the loop? Go has something like this, you might wanna go look at how they do it.

**Comment by hmontero1205** [comment]
> We might also consider allowing for other expression types (calls seem like they might be nice)

Why wouldn't that already be allowed? The grammar parses an expr for the if-condition. Function calls are exprs?
